export class Settings {
  constructor(
    public id?: number,
    public volMA?: string,
    public MovingAvg1_Enable?: boolean,
    public MovingAvg1_Time?: string,
    public MovingAvg1_Short?: string,
    public MovingAvg_Med?: string,
    public MovingAvg_Long?: string,
    public MovingAvg2_Enable?: boolean,
    public MovingAvg2_Time?: string,
    public MovingAvg2_Short?: string,
    public MovingAvg2_Med?: string,
    public MovingAvg2_Long?: string,
    public MovingAvg3_Enable?: boolean,
    public MovingAvg3_Time?: string,
    public MovingAvg3_Short?: string,
    public MovingAvg3_Med?: string,
    public MovingAvg3_Long?: string,
    public EMA1_Enable?: boolean,
    public EMA1_Time?: string,
    public EMA1_Short?: string,
    public EMA1_Med?: string,
    public EMA1_Long?: string,
    public EMA2_Enable?: boolean,
    public EMA2_Time?: string,
    public EMA2_Short?: string,
    public EMA2_Med?: string,
    public EMA2_Long?: string,
    public EMA3_Enable?: boolean,
    public EMA3_Time?: string,
    public EMA3_Short?: string,
    public EMA3_Med?: string,
    public EMA3_Long?: string,
    public RSI_Enable?: boolean,
    public RSI_1?: string,
    public RSI_2?: string,
    public RSI_3?: string,
    public MACD_Enable?: boolean,
    public MACD_1?: string,
    public MACD_2?: string,
    public MACD_3?: string,
    public AssetPairId?: number
  ) {}
}
