// <auto-generated />
using CryptoIndicatorAlerts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoIndicatorAlerts.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190317160911_CryptoIndicatorAlerts.Models.RepositoryContext")]
    partial class CryptoIndicatorAlertsModelsRepositoryContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.AssetPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseName");

                    b.Property<string>("QuoteName");

                    b.HasKey("Id");

                    b.ToTable("AssetPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
