// <auto-generated />
using System;
using CryptoIndicatorAlerts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoIndicatorAlerts.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190422222216_AddLengthToEMA")]
    partial class AddLengthToEMA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.AssetPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseName");

                    b.Property<bool>("IsSelected");

                    b.Property<string>("QuoteName");

                    b.HasKey("Id");

                    b.ToTable("AssetPairs");
                });

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.EMA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetPairId");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(9,8)");

                    b.Property<DateTime>("CloseTime");

                    b.Property<long>("CloseTimeUnix");

                    b.Property<decimal>("EMACalc")
                        .HasColumnType("decimal(9,8)");

                    b.Property<string>("Interval");

                    b.Property<int>("Length");

                    b.Property<DateTime>("OpenTime");

                    b.Property<long>("OpenTimeUnix");

                    b.HasKey("Id");

                    b.HasIndex("AssetPairId");

                    b.ToTable("EMAs");
                });

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.RSI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetPairId");

                    b.Property<decimal?>("AvgGain")
                        .HasColumnType("decimal(9,8)");

                    b.Property<decimal?>("AvgLoss")
                        .HasColumnType("decimal(9,8)");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(9,8)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(9,8)");

                    b.Property<DateTime>("CloseTime");

                    b.Property<long>("CloseTimeUnix");

                    b.Property<decimal?>("Gain")
                        .HasColumnType("decimal(9,8)");

                    b.Property<string>("Interval");

                    b.Property<decimal?>("Loss")
                        .HasColumnType("decimal(9,8)");

                    b.Property<DateTime>("OpenTime");

                    b.Property<long>("OpenTimeUnix");

                    b.Property<decimal?>("RS")
                        .HasColumnType("decimal(9,8)");

                    b.Property<decimal?>("RSICalc")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetPairId");

                    b.ToTable("RSIs");
                });

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.EMA", b =>
                {
                    b.HasOne("CryptoIndicatorAlerts.Models.AssetPair", "AssetPair")
                        .WithMany()
                        .HasForeignKey("AssetPairId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CryptoIndicatorAlerts.Models.RSI", b =>
                {
                    b.HasOne("CryptoIndicatorAlerts.Models.AssetPair", "AssetPair")
                        .WithMany("RSIs")
                        .HasForeignKey("AssetPairId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
